[tool.poetry]
name = "goit-ds-hw-01"
version = "0.1.0"
description = ""
authors = ["Oleg <lololeg2929@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
